# Generated by Django 5.1 on 2024-08-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_car_ram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
    ]
